# Generated by Django 5.0.4 on 2024-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('isbn', models.CharField(max_length=15)),
                ('details', models.TextField(max_length=250)),
            ],
        ),
    ]
