# Generated by Django 5.0.4 on 2024-04-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='store',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
